### ISSUE TITLE
Add extension to Packagist and TER

### ISSUE THREAD

**Issue by dahaupt** [ddoronenko/google-reviews#1]
Hello! Thanks for your extension, we've been using it already in several customer projects.

Is it possible to make the extension available on packagist and in the TYPO3 Extension Repository?

**Comment by ddoronenko** [comment]
@dahaupt Hello,
Just noticed your message.

Ok, I'll add it to the packagist and TER.

**Comment by ddoronenko** [comment]
@dahaupt Hello,

The package was added on the [packagist](https://packagist.org/packages/ddoronenko/google-reviews)

I can't add it to the TER as an extension with such a key already exists.

**Comment by ingeniumdesign** [comment]
Yes, plz add to the TER - Thanks!

**Comment by ddoronenko** [comment]
@ingeniumdesign @dahaupt EXT is available on TER https://extensions.typo3.org/extension/google_reviews/
Thanks, Thomas Deuling for the EXT key.

**Comment by dahaupt** [comment]
@ddoronenko Thanks for all the recent enhancements to the extension! :rocket:
