### ISSUE TITLE
The TYPO3 extension package "ddoronenko/google-reviews", does not define an extension key

### ISSUE THREAD

**Issue by dkd-kaehm** [ddoronenko/google-reviews#10]
On composer installations following warning is thrown:

```
The TYPO3 extension package "ddoronenko/google-reviews", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ComposerJson.html#extra)
```

TYPO3 v10.4

**Comment by ddoronenko** [comment]
@dkd-kaehm Hello,

Please check / use last extension version (TYPO3 v11 - v12 only). Issue should not appear anymore

**Comment by dkd-kaehm** [comment]
Currently it is on TYPO3 10.4 only.
But yes, the change fixes the issue.

It would be nice to get the change backported and the release with that for TYPO3 10.4 and 9.5.

Thanks
