### ISSUE TITLE
Partially wrong language in view of plugin

### ISSUE THREAD

**Issue by dahaupt** [ddoronenko/google-reviews#2]
I have noticed inconsistency in language in the plugin.
 
Example:
![image](https://user-images.githubusercontent.com/15915048/101350890-109b6e80-3890-11eb-97bf-7d227e9a4d3b.png)

Looking at the reviews directly in Google, both are in German. In fact, the client does not even have a single review in a different language than German.

I will look into it!

**Comment by ingeniumdesign** [comment]
yes, we have the same problem, all output is in English, but the live Reviews are in Germany

**Comment by ddoronenko** [comment]
@ingeniumdesign @dahaupt with the last EXT version you can set language (ISO2 code) for previews in the plugin configurations (FlexForm).
