### ISSUE TITLE
Feature request: Show average rating

### ISSUE THREAD

**Issue by dahaupt** [ddoronenko/google-reviews#3]
It would be great to show the average rating on top.

![image](https://user-images.githubusercontent.com/15915048/101351339-c23a9f80-3890-11eb-82cf-3d380b2ec82d.png)
Inspired by https://wordpress.org/plugins/widget-google-reviews/

**Comment by ddoronenko** [comment]
@dahaupt you can find a feature implementation in the last EXT version in the plugin configurations (FlexForm). 
"Show general place information" checkbox.
