### ISSUE TITLE
Feature request: Link to all reviews

### ISSUE THREAD

**Issue by dahaupt** [ddoronenko/google-reviews#4]
We've added an external link to all reviews within the template. Could be added generally to the plugin configuration.

Example URL: https://www.google.com/search?q=Anna+u.+Timo+Reinhardt#lrd=0x47ba71ec47df4b93:0x179f5b53ad2b5884,1

**Comment by ddoronenko** [comment]
@dahaupt Hello,

Agree, can be added (via LinkHandler field in the Flexfrom) in the next release. I'll keep you updated.

**Comment by ddoronenko** [comment]
@dahaupt you can find a feature implementation in the last EXT version in the plugin configurations (FlexForm)
