### ISSUE TITLE
Suggestion: Alternative for getContent()

### ISSUE THREAD

**Issue by ayacoo** [ddoronenko/google-reviews#6]
Code:
https://github.com/ddoronenko/google-reviews/blob/master/Classes/Service/PlaceService.php#L115

It might be better to use the core methods, because you can fall back on TYPO3 settings. Think here, for example, of a proxy or similar options. The global timeout is then also used, etc.

Doc:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Http/Index.html

**Comment by ddoronenko** [comment]
@ayacoo I agree with you, TYPO3 core methods are preferable.

I'll check and add in the next release.

**Comment by ddoronenko** [comment]
@ayacoo

Changes are added in the new 2.0 EXT version.
