### ISSUE TITLE
Suggestion: Fetch latest reviews using Google My Business API

### ISSUE THREAD

**Issue by dahaupt** [ddoronenko/google-reviews#7]
The currently used Google Places API has several disadvantages:
 - Only a maximum of 5 ratings can be queried and displayed.
 - It is not possible to display the latest reviews, because the response of the Places API contains only "relevant" reviews.
 - In case of displaying ratings with "at least x stars" it could happen that the API does not return any matching ratings at all.

It should be possible to improve this by using the **Google My Business API**. However, according to the [documentation](https://developers.google.com/my-business/reference/rest/v4/accounts.locations.reviews/list), the option to filter by language is missing. So it seems both APIs have some limitations.

Looking forward for your opinion! I could also imagine that this has already been evaluated.

**Comment by ErikN72** [comment]
I support the proposal to convert the extension to the Google My Business API!

**Comment by m10** [comment]
With the Places API it is possible to sort by newest instead of by most "relevant". [1]

This Extension is not passing the parameter to the request, instead just sorts (and filters) them afterwards depending on plugin settings. [2]

So disantvantage number 2 is not really a limitation of the API. 

[1] https://developers.google.com/maps/documentation/places/web-service/details?hl=de#reviews_sort
[2] https://github.com/ddoronenko/google-reviews/blob/master/Classes/Service/PlaceService.php#L28

**Comment by m10** [comment]
Here is an XClass that solves the limitation `most_relevant` vs `newest`:

```php
class PlaceService extends \GoogleBusiness\GoogleReviews\Service\PlaceService
{
    /**
     * returns PlaceID API response
     *
     * @param $settings
     * @return array
     */
    protected function getGoogleResponse($settings): array
    {
        $queryParams = [
            'reviews_sort' => (trim((string)$settings['sortBy']) === 'time') ? 'newest' : 'most_relevant',
            'key'          => trim((string)$settings['apiKey']),
            'place_id'     => (string)$settings['placeId'],
            'language'     => mb_strtolower((string)$settings['language'])
        ];

        $url      = $settings['apiEndpoint'] . 'json?' . http_build_query($queryParams);
        $response = $this->getUrlContent($url);

        if (isset($response['error_message']) === true) {
            $this->logger->error(
                'Error while Google place reviews getting: {errorMessage}',
                ['errorMessage' => $response['error_message']]
            );
        }

        return $response;
    }
}
```

The only change is adding `reviews_sort` parameter to the request.

**Comment by ddoronenko** [comment]
@dahaupt @m10 Hello,

Thx for the suggestion, the changes were added in the last extension version (TYPO3 v11 - v12)

See https://github.com/ddoronenko/google-reviews/blob/master/Classes/Service/PlaceService.php#L102
https://github.com/ddoronenko/google-reviews/blob/master/Configuration/FlexForms/google_reviews_pi1.xml#L76

Issue can be closed
